services:
    twig.extension.slugExt:
        class: Rudak\Slug\Twig\Extension\TwigExtension
        tags:
            - { name: twig.extension }
    rudak.slugger:
        class: Rudak\Slug\Utils\Slug

